# Generated by Django 5.2.6 on 2025-10-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='photos',
            new_name='photo',
        ),
    ]
